### ISSUE TITLE
Nooooooo

### ISSUE THREAD

**Issue by GrenderG** [javiersanzr/04AndroidAsyncTask#1]
¡No hagas [esto](https://github.com/TibiaZ/04AndroidAsyncTask/blob/master/app/src/main/java/com/example/dam2/pmm_practica_05_javiersanzrozalen/MainActivity.java#L12-L14) nunca! Puede parecer que queda guay pero no, **Javadoc** mejor.

**Comment by javiersanzr** [comment]
@GrenderG tomo nota! Gracias crack!

**Comment by GrenderG** [comment]
De nada!
